server:
  port: 7777
spring:
  main:
    allow-circular-references: true
  # 数据库信息
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    文件上传
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
      database: 0
      host:
      port:
      password:
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKeyId:
  accessKeySecret:
  endpoint :
  bucketName :